services:
  db:
    image: postgres:16
    container_name: fitness-db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: minio
    restart: unless-stopped

    ports:
      - "9000:9000" 
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    command: server /data --console-address ":9001"

    volumes:
      - minio-data:/data
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio-init:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z-cpuv1
    container_name: minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      until mc alias set local ${MINIO_URL} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do
        sleep 2
      done &&
      mc mb -p local/${MINIO_BUCKET} || true
      "
    restart: "no"


  backend:
    build: .
    container_name: app-backend
    depends_on:
      minio:
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./app-logs:/app/logs

  frontend:
    build: ./frontend
    container_name: app-frontend
    depends_on:
      - backend
    environment:
      BACKEND_URL: ${BACKEND_URL}
      FRONTEND_API_BASE_URL: ${FRONTEND_API_BASE_URL}
    ports:
      - "3000:80"

volumes:
  minio-data: 
  postgres_data:
  app-logs:
