spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fitness_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=5
spring.jpa.open-in-view=false

logging.level.root=INFO
logging.level.com.kolmir.fitness_tracker=DEBUG
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN

jwt.secret=${JWT_SECRET}
jwt.access-token.expiration=${JWT_ACCESS_TOKEN_EXPIRATION:6000000}
jwt.refresh-token.expiration=${JWT_REFRESH_TOKEN_EXPIRATION:604800000}

minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
minio.bucket=${MINIO_BUCKET:files}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:*}
